//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // /str seçeneği ile veya Visual Studio projesini yeniden kur.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Langs", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Türü kesin olarak belirtilmiş bu kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About Us benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Artado Search benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AboutSearch {
            get {
                return ResourceManager.GetString("AboutSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Academic benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Academic {
            get {
                return ResourceManager.GetString("Academic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access: You can request access to the personal data we hold about you. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AccessRight {
            get {
                return ResourceManager.GetString("AccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4. Advertising benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Advertising {
            get {
                return ResourceManager.GetString("Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By using Artado Search and our other services, you agree to the terms outlined in this Privacy Policy. Thank you for trusting Artado with your privacy. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anonymous Information by Business Partners: Our business partners may collect certain anonymous information through our services, such as anonymous IDs and search queries. This information helps improve their services and provide relevant advertisements. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AnonymousInfo {
            get {
                return ResourceManager.GetString("AnonymousInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Search is a versatile and highly customizable search engine, designed to empower users with the ability to tailor their search experience to their unique needs. This project is based on the ASP.NET Framework and is proudly open source under the AGPL v3 license. It not only offers its own search results but also integrates results from other search engines, providing a comprehensive search solution. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Artado1 {
            get {
                return ResourceManager.GetString("Artado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In a departure from the norm, Artado Search doesn&apos;t rely solely on its own search algorithms. Instead, it combines results from other search engines, presenting users with a comprehensive perspective. This unique approach ensures that users have access to a wider range of information, making it a valuable tool for those who seek diverse search results. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Artado2 {
            get {
                return ResourceManager.GetString("Artado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado goes beyond traditional search engines by offering extensive customization options. You can create personalized themes and extensions to enhance the user interface and functionality. You can find new themes, apps and games from the store. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Artado3 {
            get {
                return ResourceManager.GetString("Artado3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado does not collect any of your personal data. Artado protects your privacy as much as possible. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Artado4 {
            get {
                return ResourceManager.GetString("Artado4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your highly customizable search engine 🔎 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Artado_Custom {
            get {
                return ResourceManager.GetString("Artado_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep your data to yourself 🔒 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Artado_Privacy {
            get {
                return ResourceManager.GetString("Artado_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This page has not been translated into all languages. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Azerbaijani benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Azer {
            get {
                return ResourceManager.GetString("Azer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wallpaper benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can put any picture you want in the background. You can reset the background by leaving it blank. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Back_exp {
            get {
                return ResourceManager.GetString("Back_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basic Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Basics {
            get {
                return ResourceManager.GetString("Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This feature is not currently available as Artado Search is still in beta. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado results may be insufficient since it is still in beta. You can use the results of Google or other search engines by selecting them from the panel above. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BetaResults {
            get {
                return ResourceManager.GetString("BetaResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blog benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bosnian benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Bosnian {
            get {
                return ResourceManager.GetString("Bosnian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bulgarian benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Bulgarian {
            get {
                return ResourceManager.GetString("Bulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the link of the image you want to put in the background. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string B_4 {
            get {
                return ResourceManager.GetString("B_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Categories benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can change the location of the search categories. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Cat_exp {
            get {
                return ResourceManager.GetString("Cat_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chinese benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Classic benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Classic {
            get {
                return ResourceManager.GetString("Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Colorful benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Colorful {
            get {
                return ResourceManager.GetString("Colorful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you have any questions or concerns about this Privacy Policy, please contact us at: arda@artadosearch.com or support@artadosearch.com benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To exercise any of these rights, please contact us at arda@artadosearch.com. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ContactRights {
            get {
                return ResourceManager.GetString("ContactRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8. Contact Us benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cookies benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Cookies1 {
            get {
                return ResourceManager.GetString("Cookies1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Correction: You can request corrections to any inaccurate or incomplete data. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CorrectionRight {
            get {
                return ResourceManager.GetString("CorrectionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Create_Profile {
            get {
                return ResourceManager.GetString("Create_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom CSS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CustomCSS {
            get {
                return ResourceManager.GetString("CustomCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can customize and create your own theme for Artado with writing CSS code. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CustomCSS_exp {
            get {
                return ResourceManager.GetString("CustomCSS_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can manage the extensions you use here. You can also find more extensions from the Artado Store. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CustomExt_exp {
            get {
                return ResourceManager.GetString("CustomExt_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customise as you like 🎨 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Customise_as {
            get {
                return ResourceManager.GetString("Customise_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customization benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Customization {
            get {
                return ResourceManager.GetString("Customization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Extension benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CustomJS {
            get {
                return ResourceManager.GetString("CustomJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can customize and create your own extension for Artado with writing Javascript code. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CustomJS_exp {
            get {
                return ResourceManager.GetString("CustomJS_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Themes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CustomThemes {
            get {
                return ResourceManager.GetString("CustomThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can manage the themes you use here. Also you can find more themes in Artado Store. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CustomTheme_exp {
            get {
                return ResourceManager.GetString("CustomTheme_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5. Data Protection and Security benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DataProtection {
            get {
                return ResourceManager.GetString("DataProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Default2 {
            get {
                return ResourceManager.GetString("Default2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to default settings. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Default3 {
            get {
                return ResourceManager.GetString("Default3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deletion: You can request the deletion of your personal data, subject to certain legal requirements. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DeletionRight {
            get {
                return ResourceManager.GetString("DeletionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorry! We are currently experiencing a problem. Artado will be active again soon. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a profile name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extensions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movie benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Film {
            get {
                return ResourceManager.GetString("Film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   French benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   German benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to the Store benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GoStore {
            get {
                return ResourceManager.GetString("GoStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Greek benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Greek {
            get {
                return ResourceManager.GetString("Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hungarian benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Hungarian {
            get {
                return ResourceManager.GetString("Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Images benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. Information We Collect benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string InfoWeCollect {
            get {
                return ResourceManager.GetString("InfoWeCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado is committed to protecting your privacy. This Privacy Policy outlines how we collect, use, and protect your personal information. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Italian benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kazakh benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Kazakh {
            get {
                return ResourceManager.GetString("Kazakh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korean benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kyrgyz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Kyrgyz {
            get {
                return ResourceManager.GetString("Kyrgyz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Languages benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the language you are using Artado Search. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Lang_exp {
            get {
                return ResourceManager.GetString("Lang_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Updated: 16.04.2024 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logo benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can change Artado Search&apos;s logo as you wish. More logos can be found in the store. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Logo_exp {
            get {
                return ResourceManager.GetString("Logo_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macedonian benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Macedonian {
            get {
                return ResourceManager.GetString("Macedonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manifesto benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Manifest {
            get {
                return ResourceManager.GetString("Manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artado Manifesto benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Manifesto1 {
            get {
                return ResourceManager.GetString("Manifesto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We advocate an internet where everyone can freely exchange information, respect personal data and express ideas without any censorship. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Manifesto2 {
            get {
                return ResourceManager.GetString("Manifesto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More than one source🔥 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string More_than {
            get {
                return ResourceManager.GetString("More_than", resourceCulture);
            }
        }
        
        /// <summary>
        ///   News benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Night benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Storage by Artado: Artado does not store any search queries made by users. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoStorageByArtado {
            get {
                return ResourceManager.GetString("NoStorageByArtado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Objection: You can object to the processing of your personal data in certain circumstances. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ObjectionRight {
            get {
                return ResourceManager.GetString("ObjectionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old Logo benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Source benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OpenSource {
            get {
                return ResourceManager.GetString("OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy Policy - Artado Search benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7. Changes to This Privacy Policy benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PolicyChanges {
            get {
                return ResourceManager.GetString("PolicyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We may update this Privacy Policy from time to time. We will notify you of any significant changes by posting the new Privacy Policy on our website. You are advised to review this Privacy Policy periodically for any changes. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PolicyChangesDetails {
            get {
                return ResourceManager.GetString("PolicyChangesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Portuguese benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pride benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Pride {
            get {
                return ResourceManager.GetString("Pride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profiles benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profiles are a way to store your Artado configurations in the cloud. You can save your customization to the cloud and use it in another device or you can share your customization with your friends. Also by logging in your Artado account you can sync your profiles. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Profiles_exp {
            get {
                return ResourceManager.GetString("Profiles_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Profile_Name {
            get {
                return ResourceManager.GetString("Profile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Our Projects benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projects by this developer: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProjectsByThisDev {
            get {
                return ResourceManager.GetString("ProjectsByThisDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Results benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Under the KVKK(Turkish Personal Data Protection Law), you have the following rights regarding your personal data: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RightsExplanation {
            get {
                return ResourceManager.GetString("RightsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Russian benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3. Search Data benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SearchData {
            get {
                return ResourceManager.GetString("SearchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We implement industry-standard security measures to protect your personal information. However, please note that no method of transmission over the internet or electronic storage is completely secure. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SecurityMeasures {
            get {
                return ResourceManager.GetString("SecurityMeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serbian benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign in benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explore Internet! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spanish benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync with your Artado account benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Themes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can find more themes in Artado Store. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Theme_exp {
            get {
                return ResourceManager.GetString("Theme_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Third-Party Collection: Our business partners and result providers may collect and store anonymous search queries to improve their services and for analytics purposes. If user only use Artado results and disable the advertisements from settings no one can know what user searched. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ThirdPartyCollection {
            get {
                return ResourceManager.GetString("ThirdPartyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy Policy - Artado Search benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turkish benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turkmen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Turkmen {
            get {
                return ResourceManager.GetString("Turkmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ukrainian benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unique User ID: We assign a unique ID to each user for the purpose of delivering ads. This ID is deleted when you close Artado Search unless you specifically choose to retain it. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UniqueUserId {
            get {
                return ResourceManager.GetString("UniqueUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anonymous Information: Anonymous information collected by our business partners may be used for analytics, improving services, and delivering personalized advertisements. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UseAnonymousInfo {
            get {
                return ResourceManager.GetString("UseAnonymousInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2. Use of Information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UseOfInfo {
            get {
                return ResourceManager.GetString("UseOfInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User-Provided Information: We only collect personal information that you willingly provide to us, such as your email address when you sign up for our services or newsletters. We may also collect further information upon lawful requests made by government or legislative authorities. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UserProvidedInfo {
            get {
                return ResourceManager.GetString("UserProvidedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6. User Rights benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UserRights {
            get {
                return ResourceManager.GetString("UserRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User-Provided Information: Any personal information you provide is used solely for the purpose you provided it for, such as receiving newsletters or updates from Artado. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UseUserProvidedInfo {
            get {
                return ResourceManager.GetString("UseUserProvidedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uzbek benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Uzbek {
            get {
                return ResourceManager.GetString("Uzbek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
