//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artadosearch {
	
	
	public partial class test {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox TextBox1;
		
		protected System.Web.UI.WebControls.TextBox Salt;
		
		protected System.Web.UI.WebControls.Button Şifrele;
		
		protected System.Web.UI.WebControls.Button Çöz;
		
		protected System.Web.UI.WebControls.Label Sonuc;
		
		protected System.Web.UI.WebControls.Label Hashed;
		
		protected System.Web.UI.WebControls.Button Button1;
	}
}
